### PR TITLE
Update index.css

### PR DESCRIPTION
**Pull request by egelmex**
add space to break up sponsors

### CODE REVIEW

**Comment by egelmex** [comment]
I don't know how to test this, the style was added blind

**Comment by vext01** [comment]
@egelmex run GNU make in the website sub-dir and it invokes a web-server.

**Comment by egelmex** [comment]
I am not going to be at a machine before Saturday

**Comment by vext01** [comment]
Thanks Mex, this looks much better. I've deployed this.

Closing because I had to cherry-pick your commit into my own up-to-date branch and push from there.

image

**Pull request closed without merging**
